/** Basic controls */
export const CHANGE_EMERGENCY_STOP = 'CHANGE_EMERGENCY_STOP'
export const CHANGE_POD_START = 'CHANGE_POD_START'
export const CHANGE_SPEED = 'CHANGE_SPEED'
export const CHANGE_ACCELERATION = 'CHANGE_ACCELERATION'
export const CHANGE_BRAKE = 'CHANGE_BRAKE'
export const CHANGE_LEVITATION = 'CHANGE_LEVITATION'

/** Basic control states reported back */
export const UPDATE_EMERGENCY_STOP = 'UPDATE_EMERGENCY_STOP'
export const UPDATE_POD_START = 'UPDATE_POD_START'
export const UPDATE_LEVITATION = 'UPDATE_LEVITATION'
export const UPDATE_BRAKE = 'UPDATE_BRAKE'
/** Setting controls */
export const CHANGE_CONTROL_MANUAL = 'CHANGE_CONTROL_MANUAL'
export const CHANGE_CONTROL_INSTANT = 'CHANGE_CONTROL_INSTANT'
export const CHANGE_KEEP_LAST_DATA = 'CHANGE_KEEP_LAST_DATA'

/** General datums */
export const UPDATE_SPEED = 'UPDATE_SPEED_DATA'
export const UPDATE_ACCELERATION = 'UPDATE_ACCELERATION'

export const UPDATE_AIR_TANK_LEVEL = 'UPDATE_AIR_TANK_LEVEL'
export const UPDATE_BATTERY = 'UPDATE_BATTERY'
export const UPDATE_TEMP = 'UPDATE_TEMP'
export const UPDATE_AIR_TANK_PRESSURE = 'UPDATE_AIR_TANK_PRESSURE'
export const UPDATE_DISTANCE = 'UPDATE_DISTANCE'
export const UPDATE_IMU = 'UPDATE_IMU'
export const UPDATE_IMU_ROTATION = 'UPDATE_IMU_ROTATION'

/** Change connection details */
export const UPDATE_CONNECTION_STATE = 'UPDATE_CONNECTION_STATE'
export const UPDATE_CONNECTION_LATENCY = 'UPDATE_CONNECTION_LATENCY'
export const UPDATE_CONNECTION_STRENGTH = 'UPDATE_CONNECTION_STRENGTH'
