export const SPEED = 'speed'
export const ACCELERATION = 'acceleration'
export const AIR_TANK_LEVEL = 'airTankLevel'
export const BATTERY_LEVEL = 'batteryLevel'
export const TEMPERATURE = 'temp'
export const DISTANCE = 'distance'
export const IMU = 'IMU'
