export const EMERGENCY_STOP = 'emg' // 0 or 1
export const BRAKE = 'brk'          // 0 or 1
export const SPEED = 'spd'          // 0 or 100
export const MANUAL_CONTROL = 'man' // 0 or 1
export const AUTO_CONTROL = 'auto'
export const SCRIPT_CONTROL = 'scpt'
export const AUTO = 'auto'          // 0 or 1
export const BALL_VALVE = 'bv'      // 0 or 1
export const DPR = 'dpr'            // 0 or 1
export const HEART_BEAT_CHECK = 'check' // 1
export const CONNECT = 'connect'        // 0 or 1
export const RESTART_SAVED = 'rests'    // 1
export const RESTART_UNSAVED = 'restus' // 1
export const STOP = 'stop'              // 1
export const DRIVE_TRAIN_SPEED = 'spddrive'
export const MAGWHEEL_SPEED = 'spdmag'
export const ACCELERATION = 'acceleration'
export const LEVITATION = 'levitation'
export const START = 'start'
export const CONNECT_ARDUINO = 'connect'
export const DROP = 'ewr'
