export const DROP = 'drop'
export const BRAKE = 'brk' // 0 or 1
export const BATTERY_24 = 'battery24'
export const BATTERY_48 = 'battery48'
export const DRIVE_TRAIN_SPEED = 'spddrive'
export const BALL_VALVE = 'bv' // 0 or 1
export const MAGWHEEL_SPEED = 'spdmag'
export const STATE = 'state'
export const DPR = 'dpr' // 0 or 1
