export const ACCELERATION = 'accel'
export const BRAKE = 'brake'
export const EMERGENCY_STOP = 'emergencyStop'
export const LEVITATION = 'levitation'
export const MANUAL_CONTROL = 'manualControl'
export const SPEED = 'speed'
export const START = 'start'
